### ISSUE TITLE
[Suggestion] Shape Lights and Light Falloff

### ISSUE THREAD

**Issue by Yeahyay** [chicogamedev/Luven#1]
Shape Lights:
Lights of differing shape.
- Basic circle light
- Rectangle light
- Cone light (A slice of a circle)

Falloff:
A circle light with radius 100 and falloff radius 100:
- the objects withing 100 units of the light are at maximum brightness
- objects past 100 units (radius) but within the falloff radius (radius+falloff) are linearly interpolated from brightness 1 to brightness 0
- objects past the 200 units (radius + falloff radius) have 0 brightness

Example project visualizing what I mean by light falloff.
[basic lighting concept.zip](https://github.com/chicogamedev/Luven/files/2898363/basic.lighting.concept.zip)

**Comment by halsten-dev** [comment]
Hi,

Thanks for your example, I'm afraid this is not a "minimal" feature but I'll see what I can do.

For the Cone light just to be sure to understand each others. 

Is it one of these shape your meaning ?

![flashlight1](https://user-images.githubusercontent.com/6854475/53314411-75a1f200-38be-11e9-9311-cd956bd920c9.png)
![flashlight2](https://user-images.githubusercontent.com/6854475/53314412-75a1f200-38be-11e9-8ba6-4419ccc5fa36.png)

If not, please draw it just to give me an idea. 

P.S : Of course circle lights are already in x) 

Thanks !

**Comment by flamendless** [comment]
Yeah, a flashlight beam would be really useful for 2d platformer style

**Comment by Yeahyay** [comment]
I just listed circle lights so the list is complete and I get everything right. :p
By cone light I meant the sector of a circle:
![cone lighting](https://user-images.githubusercontent.com/34212037/53315888-82f5b700-3893-11e9-8cd2-6a4d9864a46e.png)
If that's too tricky to implement, a triangle would work too.
Also ellipses would be cool after seeing the second image.
For the falloff, I feel like one extra variable is simple enough for this to still be minimalist; I see it as a simple yet powerful addition, like cone lights. If you feel that it goes beyond the scope of the library, I can live without it.
Thank you for considering this!

**Comment by halsten-dev** [comment]
Ok ok thanks for precision !

> Thank you for considering this!

With pleasure !

But this falloff, is that not what a light system have to do by default ? I mean when you're light source is away from something there is less light and so on, that just the light power, no ?

Because you example are just a mathematical simulation of lights. I mean in Luven you're not saying : that object have to be lit at this distance.
 
but instead : the light source is here and have this power, if the object is far enough it won't be lit. 

Am I missing something ? 😄

**Comment by Yeahyay** [comment]
The first radius, the object will always be fully lit. The falloff is similar to the power variable. The falloff and radius would be used artistically; say if I wanted a light to be big but fall off very quickly: high radius, low falloff. A default light as it is in Luven right now is essentially 0 radius with the falloff radius being the power variable. In my example, setting the radius to 0 and falloff radius to any number simulates what happens in Luven.

**Comment by halsten-dev** [comment]
I get it better now, I will probably have a bit of trouble now that I'm going to leave the shader behind (cause of performance) and work only with image. 

But with that being said I very very intrigued by this. Have you any artistic example where you saw the use of something like that ? 😀

**Comment by Yeahyay** [comment]
A spotlight with 0 falloff could highlight a character.
A spotlight with a radius of 50 and falloff of 50 looks brighter than a normal Luven spotlight with a power of 100 (0 radius 100 falloff). This could be used to express that a light is extra bright.

A cone light with a high radius and even higher falloff could simulate a flashlight.
A cone light could also be used to highlight a character.

**Comment by halsten-dev** [comment]
Ok ok I've now fully understood your request. 

I let you know if I'll do it ! 

Have a wonderful day ✌️

**Comment by flamendless** [comment]
Just gonna ask here.

This lighting can be done with using a texture + canvas blending, similar to my Going Home game. But would this be more efficient and more powerful with luven?
![](https://i.imgur.com/Uyrjb2h.jpg)


Is this one the same with the above but with just different "value". This kind of lighting is what i want to achieve, i really hope it could be done easier with luven.
![](https://i.imgur.com/fOo7qQy.jpg)

**Comment by halsten-dev** [comment]
Waouw nice screenshots. 
I will dig into adding more feature and your screenshot helps a lot to visualize. 

> This kind of lighting is what i want to achieve, i really hope it could be done easier with luven.

For the moment absolutely not achievable. But in later releases probably. 
If you agree, you can show me how you actually manage your lights, so I'll get a better idea if Luven will be able to simplify your life 😃 If you don't want to publicly leak some lines of codes of your game, we can do this in private chat (twitter or private message on love2D forums)

> But would this be more efficient and more powerful with luven?

Now for performance, I think that nothing is more efficient that totally custom feature that fit exactly your need, but the ways I'm actually reworking Luven, you would probably be able to use it without any drawback.


Please give me some time to make Luven able to satisfy your needs. ✌️

**Comment by flamendless** [comment]
The code i used in my first löve game is not that original to be private about, it's actually just from the light effect I saw on the löve forum.

To be honest I am not sure where it is in my codebase since it's a mess (first time lua and lövethat's why).

If you want, i will find the canvas + blend modes löve zip I found in the forums (if that's what you meant by the "how i did my lights") 

And yeah, I'm gonna wait for this project since it's more promising compared to other lighting system. Also, you are very into developing and improving it, which is rare for me.

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by halsten-dev** [comment]
Ok ok yes this would be useful to get the mindset 😄 

Thanks !

**Comment by halsten-dev** [comment]
So Luven v1.1 went out !

And I think I have deliver for this feature request, except for the light falloff and here is why : 

Actually I'm working with sprites so no lights are really dynamically calculated, except for size or power and so on. 

But with `Luven.registerLightShape()` everything you guys can dream about will be possible, in my opinion. So please try it and give me feedback if it fits what you guys were expecting. 

At least for my game Luven is working wonderfully well.


Regards

**Comment by halsten-dev** [comment]
10 days without news I consider this issue closed 😄

**Comment by flamendless** [comment]
I dont have the time yet to test this library... But I will really test this out once i have the time

**Comment by halsten-dev** [comment]
Thanks a lot for your interest ! Can't wait to get more feedback.
