### ISSUE TITLE
Can't disable camera integration

### ISSUE THREAD

**Issue by togfoxy** [chicogamedev/Luven#6]
This doc:
luven.init( [ screenWidth ], [ screenHeight ], [ useCamera ] ) :

is incorrect as luven.init accepts two parameters and not three.

**Comment by slime73** [comment]
It looks like it takes 3 to me, unless there's something I'm missing? https://github.com/chicogamedev/Luven/blob/master/luven/luven.lua#L317-L324

& https://github.com/chicogamedev/Luven/blob/master/luven/luven.lua#L363-L366

**Comment by togfoxy** [comment]
Yes. You're right I'm looking at this function:
function luven.camera:init(x, y)

which of course is different. I'll close the issue. Thanks.
